let courseArr = ["Amit Kumar", "Raghav Sharma", "25", "Python"];
console.log(courseArr);
courseArr.push("oops");
console.log(courseArr);
courseArr.pop();
console.log(courseArr);
courseArr.unshift("java");
console.log(courseArr);
courseArr.shift();
console.log(courseArr);
